{-# LANGUAGE InstanceSigs, ScopedTypeVariables #-}

module Solution where

import Data.Foldable (toList, foldr)
import System.Exit (exitFailure)

-- | Набор значений: пустой, однерка, или 2 последующих.
data Sequence a = Empty | Single a | Append (Sequence a) (Sequence a)

-- * 1. Functor

instance Functor Sequence where
  fmap :: (a -> b) -> Sequence a -> Sequence b
  fmap _ Empty = Empty
  fmap f (Single x) = Single (f x)
  fmap f (Append l r) = Append (fmap f l) (fmap f r)

-- * 2. Foldable (слева направа - левая ветка перед правой)

instance Foldable Sequence where
  foldMap :: Monoid m => (a -> m) -> Sequence a -> m
  foldMap _ Empty = mempty
  foldMap f (Single x) = f x
  foldMap f (Append l r) = foldMap f l <> foldMap f r

seqToList :: Sequence a -> [a]
seqToList = toList

seqLength :: Sequence a -> Int
seqLength = length

-- * 3. Semigroup and Monoid

instance Semigroup (Sequence a) where
  (<>) :: Sequence a -> Sequence a -> Sequence a
  (<>) = Append

instance Monoid (Sequence a) where
  mempty :: Sequence a
  mempty = Empty

-- * 4. Tail recursion: search with explicit stack

tailElem :: forall a. Eq a => a -> Sequence a -> Bool
tailElem x = go []
  where
    go :: [Sequence a] -> Sequence a -> Bool
    go stk Empty = case stk of
      [] -> False
      s : ss -> go ss s
    go stk (Single y)
      | x == y = True
      | otherwise = go stk Empty
    go stk (Append l r) = go (r : stk) l

-- * 5. Tail recursion: flatten to list

tailToList :: forall a. Sequence a -> [a]
tailToList s = go s [] []
  where
    go :: Sequence a -> [Sequence a] -> [a] -> [a]
    go Empty stk acc = case stk of
      [] -> reverse acc
      s : ss -> go s ss acc
    go (Single y) stk acc = go Empty stk (y : acc)
    go (Append l r) stk acc = go l (r : stk) acc

-- * 6. RPN

data Token = TNum Int | TAdd | TSub | TMul | TDiv

tailRPN :: [Token] -> Maybe Int
tailRPN = go []
  where
    go :: [Int] -> [Token] -> Maybe Int
    go stack [] = case stack of
      [n] -> Just n
      _ -> Nothing
    go stack (TNum n : ts) = go (n : stack) ts
    go stack (TAdd : ts) = case stack of
      b : a : rest -> go (a + b : rest) ts
      _ -> Nothing
    go stack (TSub : ts) = case stack of
      b : a : rest -> go (a - b : rest) ts
      _ -> Nothing
    go stack (TMul : ts) = case stack of
      b : a : rest -> go (a * b : rest) ts
      _ -> Nothing
    go stack (TDiv : ts) = case stack of
      b : a : rest
        | b == 0 -> Nothing
        | otherwise -> go (a `div` b : rest) ts
      _ -> Nothing

-- * 7. Folds (без рекурсии)

myReverse :: [a] -> [a]
myReverse = foldl (flip (:)) []

myTakeWhile :: (a -> Bool) -> [a] -> [a]
myTakeWhile p = foldr step []
  where
    step x r
      | p x = x : r
      | otherwise = []

decimal :: [Int] -> Int
decimal = foldl (\acc d -> acc * 10 + d) 0

-- * 8. Run-length encoding

encode :: Eq a => [a] -> [(a, Int)]
encode = foldr step []
  where
    step x [] = [(x, 1)]
    step x ((y, n) : ys)
      | x == y = (y, n + 1) : ys
      | otherwise = (x, 1) : (y, n) : ys

decode :: [(a, Int)] -> [a]
decode = foldr (\(x, n) acc -> replicate n x ++ acc) []

-- * Tests generated by AI

-- | Sample tree: @1@, then @2@, then @3@ left-to-right.
sampleSeq :: Sequence Int
sampleSeq = Append (Append (Single 1) (Single 2)) (Single 3)

main :: IO ()
main = do
  let rleSample = "aaabccca" :: String
      rleEnc = [('a', 3), ('b', 1), ('c', 3), ('a', 1)] :: [(Char, Int)]
      tests :: [(String, Bool)]
      tests =
        [ ("1. Functor: fmap on Single", seqToList (fmap (* 2) (Single 5)) == [10])
        ,
          ( "1. Functor: fmap on nested Append"
          , seqToList (fmap (+ 1) sampleSeq) == [2, 3, 4]
          )
        ,
          ( "2. Foldable: seqToList left-to-right"
          , seqToList sampleSeq == [1, 2, 3]
          )
        , ("2. Foldable: seqLength", seqLength sampleSeq == 3)
        ,
          ( "2. Foldable: foldr agrees with seqToList"
          , foldr (:) [] sampleSeq == seqToList sampleSeq
          )
        ,
          ( "3. Monoid: mempty"
          , seqToList (mempty `mappend` Single 'x' :: Sequence Char) == "x"
          )
        ,
          ( "3. Semigroup: (<>) order"
          , seqToList (Single (1 :: Int) <> Single 2 <> Single 3) == [1, 2, 3]
          )
        , ("4. tailElem: present", tailElem (2 :: Int) sampleSeq)
        , ("4. tailElem: absent", not (tailElem (0 :: Int) sampleSeq))
        , ("5. tailToList vs seqToList", tailToList sampleSeq == seqToList sampleSeq)
        , ("RPN: add", tailRPN [TNum 3, TNum 4, TAdd] == Just 7)
        , ("RPN: subtract (a - b)", tailRPN [TNum 10, TNum 3, TSub] == Just 7)
        , ("RPN: multiply", tailRPN [TNum 6, TNum 7, TMul] == Just 42)
        , ("RPN: divide", tailRPN [TNum 20, TNum 4, TDiv] == Just 5)
        , ("RPN: division by zero", tailRPN [TNum 1, TNum 0, TDiv] == Nothing)
        , ("RPN: too few operands", tailRPN [TAdd] == Nothing)
        , ("RPN: extra values on stack", tailRPN [TNum 1, TNum 2] == Nothing)
        , ("6(a). myReverse", myReverse [1, 2, 3 :: Int] == [3, 2, 1])
        , ("6(b). myTakeWhile", myTakeWhile even [2, 4, 3, 6 :: Int] == [2, 4])
        , ("6(c). decimal", decimal [1, 2, 3] == 123)
        , ("7(a). encode", encode rleSample == rleEnc)
        , ("7(b). decode", decode rleEnc == rleSample)
        , ("7. encode/decode roundtrip", decode (encode rleSample) == rleSample)
        ]
  mapM_
    ( \(label, ok) ->
        putStrLn (label ++ if ok then " — OK" else " — FAIL")
    )
    tests
  putStrLn "---"
  let failed = length (filter (not . snd) tests)
  if failed == 0
    then putStrLn ("All " ++ show (length tests) ++ " tests passed.")
    else do
      putStrLn (show failed ++ " test(s) failed.")
      exitFailure
